// Generated by github.com/cool112/gogame/utils/cmd/protoc-reg-plugin
// DO NOT EDIT!
// Source: log_common.proto

package common

import (
	"github.com/cool112/gogame/proto"
	"github.com/davyxu/cellnet"
	"reflect"
	_ "github.com/davyxu/cellnet/codec/gogopb"
	"github.com/davyxu/cellnet/codec"
)

func init() {

	// log_common.proto
	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("gogopb"),
		Type:  reflect.TypeOf((*LogCommon)(nil)).Elem(),
		ID:    proto.LOG_COMMON,
	})
}
